import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class IdiomaService {

    
    listaDeIdiomas(): any[]{
        return [
            {"indice": 0, "idiomaEnCastellano": "Afrikáans", "idiomaOroginal": "Afrikaans "},
            {"indice": 1, "idiomaEnCastellano": "Albanés", "idiomaOroginal": "shqiptar "},
            {"indice": 2, "idiomaEnCastellano": "Alemán", "idiomaOroginal": "Deutsch "},
            {"indice": 3, "idiomaEnCastellano": "Amárico", "idiomaOroginal": "አማርኛ "},
            {"indice": 4, "idiomaEnCastellano": "Árabe", "idiomaOroginal": "العربية"},
            {"indice": 5, "idiomaEnCastellano": "Armenio", "idiomaOroginal": "Հայերեն "},
            {"indice": 6, "idiomaEnCastellano": "Azerbaiyano", "idiomaOroginal": "Azərbaycan "},
            {"indice": 7, "idiomaEnCastellano": "Bengalí", "idiomaOroginal": "বাঙালি "},
            {"indice": 8, "idiomaEnCastellano": "Bielorruso", "idiomaOroginal": "Беларус "},
            {"indice": 9, "idiomaEnCastellano": "Birmano", "idiomaOroginal": "မြန်မာ "},
            {"indice": 10, "idiomaEnCastellano": "Bosnio", "idiomaOroginal": "Bosanski "},
            {"indice": 11, "idiomaEnCastellano": "Búlgaro", "idiomaOroginal": "български "},
            {"indice": 12, "idiomaEnCastellano": "Canarés", "idiomaOroginal": "ಕನ್ನಡ "},
            {"indice": 13, "idiomaEnCastellano": "Catalán", "idiomaOroginal": "català"},
            {"indice": 14, "idiomaEnCastellano": "Cebuano", "idiomaOroginal": "Cebuano"},
            {"indice": 15, "idiomaEnCastellano": "Checo", "idiomaOroginal": "Česky"},
            {"indice": 16, "idiomaEnCastellano": "Chino (Simplificado)", "idiomaOroginal":   "中文（简体）"},
            {"indice": 17, "idiomaEnCastellano": "Chino (Tradicional)", "idiomaOroginal":  "中文（繁體）"},
            {"indice": 18, "idiomaEnCastellano": "Cingalés", "idiomaOroginal": "සිංහල"},
            {"indice": 19, "idiomaEnCastellano": "Coreano", "idiomaOroginal": "한국어"},
            {"indice": 20, "idiomaEnCastellano": "Corso", "idiomaOroginal": "Corsu"},
            {"indice": 21, "idiomaEnCastellano": "Criollo", "idiomaOroginal": "haitiano Kreyòl Ayisyen "},
            {"indice": 22, "idiomaEnCastellano": "Croata", "idiomaOroginal": "hrvatski"},
            {"indice": 23, "idiomaEnCastellano": "Danés", "idiomaOroginal": "dansk"},
            {"indice": 24, "idiomaEnCastellano": "Eslovaco", "idiomaOroginal": "slovenský"},
            {"indice": 25, "idiomaEnCastellano": "Esloveno", "idiomaOroginal": "Slovensko"},
            {"indice": 26, "idiomaEnCastellano": "Español", "idiomaOroginal": "Español", "direccion" : "de izquieda a derecha"},
            {"indice": 27, "idiomaEnCastellano": "Esperanto", "idiomaOroginal": "Esperanto"},
            {"indice": 28, "idiomaEnCastellano": "Estonio", "idiomaOroginal": "Eestlane"},
            {"indice": 29, "idiomaEnCastellano": "Euskera", "idiomaOroginal": "Euskera"},
            {"indice": 30, "idiomaEnCastellano": "Finés", "idiomaOroginal": "suomalainen"},
            {"indice": 31, "idiomaEnCastellano": "Francés", "idiomaOroginal": "Le français"},
            {"indice": 32, "idiomaEnCastellano": "Frisón", "idiomaOroginal": "occidental Westerlauwersk"},
            {"indice": 33, "idiomaEnCastellano": "Gaélico", "idiomaOroginal": "escocés Gàidhlig na h-Alba"},
            {"indice": 34, "idiomaEnCastellano": "Galés", "idiomaOroginal": "Cymraeg"},
            {"indice": 35, "idiomaEnCastellano": "Gallego", "idiomaOroginal": "Galego "},
            {"indice": 36, "idiomaEnCastellano": "Georgiano", "idiomaOroginal": "ქართული"},
            {"indice": 37, "idiomaEnCastellano": "Griego", "idiomaOroginal": "Ελληνικά"},
            {"indice": 38, "idiomaEnCastellano": "Guyaratí", "idiomaOroginal": "ગુજરાતí "},
            {"indice": 39, "idiomaEnCastellano": "Hausa", "idiomaOroginal": "Hausa "},
            {"indice": 40, "idiomaEnCastellano": "Hawaiano", "idiomaOroginal": "ʻ .lelo Hawaiʻi"},
            {"indice": 41, "idiomaEnCastellano": "Hebreo", "idiomaOroginal": "עברית "},
            {"indice": 42, "idiomaEnCastellano": "Hindi", "idiomaOroginal": "हिन्दी "},
            {"indice": 43, "idiomaEnCastellano": "Hmong", "idiomaOroginal": "Hmong "},
            {"indice": 44, "idiomaEnCastellano": "Húngaro", "idiomaOroginal": "magyar "},
            {"indice": 45, "idiomaEnCastellano": "Igbo", "idiomaOroginal": "Ndi Igbo"},
            {"indice": 46, "idiomaEnCastellano": "Indonesio", "idiomaOroginal": "Orang indonesia"},
            {"indice": 47, "idiomaEnCastellano": "Inglés", "idiomaOroginal": "English "},
            {"indice": 48, "idiomaEnCastellano": "Irlandés", "idiomaOroginal": "Gaeilge "},
            {"indice": 49, "idiomaEnCastellano": "Islandés", "idiomaOroginal": "Íslensku "},
            {"indice": 50, "idiomaEnCastellano": "Italiano", "idiomaOroginal": "italiano "},
            {"indice": 51, "idiomaEnCastellano": "Japonés", "idiomaOroginal": "日本語 "},
            {"indice": 52, "idiomaEnCastellano": "Javanés", "idiomaOroginal": "Basa jawa"},
            {"indice": 53, "idiomaEnCastellano": "Jemer", "idiomaOroginal": "ខ្មែរ។ "},
            {"indice": 54, "idiomaEnCastellano": "Kazajo", "idiomaOroginal": "Қазақ "},
            {"indice": 55, "idiomaEnCastellano": "Kirguís", "idiomaOroginal": "Кыргызстандык "},
            {"indice": 56, "idiomaEnCastellano": "Kurdo", "idiomaOroginal": "Kurdî"},
            {"indice": 57, "idiomaEnCastellano": "Lao", "idiomaOroginal": "ລາວ "},
            {"indice": 58, "idiomaEnCastellano": "Latín", "idiomaOroginal": "Latine"},
            {"indice": 59, "idiomaEnCastellano": "Letón", "idiomaOroginal": "Latvietis"},
            {"indice": 60, "idiomaEnCastellano": "Lituano", "idiomaOroginal": "Lietuvis"},
            {"indice": 61, "idiomaEnCastellano": "Luxemburgués", "idiomaOroginal": "Lëtzebuergesch"},
            {"indice": 62, "idiomaEnCastellano": "Macedonio", "idiomaOroginal": "Македонски"},
            {"indice": 63, "idiomaEnCastellano": "Malayalam", "idiomaOroginal": "മലയാളം "},
            {"indice": 64, "idiomaEnCastellano": "Malayo", "idiomaOroginal": "Melayu"},
            {"indice": 65, "idiomaEnCastellano": "Malgache", "idiomaOroginal": "Malgache"},
            {"indice": 66, "idiomaEnCastellano": "Maltés", "idiomaOroginal": "Malti"},
            {"indice": 67, "idiomaEnCastellano": "Maorí", "idiomaOroginal": "Maori"},
            {"indice": 68, "idiomaEnCastellano": "Maratí", "idiomaOroginal":  "मराठी"},
            {"indice": 69, "idiomaEnCastellano": "Mongol", "idiomaOroginal": "Монгол"},
            {"indice": 70, "idiomaEnCastellano": "Neerlandés", "idiomaOroginal": "Nederlands"},
            {"indice": 71, "idiomaEnCastellano": "Nepalí", "idiomaOroginal": "नेपाली"},
            {"indice": 72, "idiomaEnCastellano": "Noruego", "idiomaOroginal": "norsk"},
            {"indice": 73, "idiomaEnCastellano": "Nyanja", "idiomaOroginal": "Nyanja"},
            {"indice": 74, "idiomaEnCastellano": "Panyabí", "idiomaOroginal": "ਪੰਜਾਬੀ"},
            {"indice": 75, "idiomaEnCastellano": "Pastún", "idiomaOroginal": "پښتو"},
            {"indice": 76, "idiomaEnCastellano": "Persa", "idiomaOroginal": "فارسی"},
            {"indice": 77, "idiomaEnCastellano": "Polaco", "idiomaOroginal": "Polski"},
            {"indice": 78, "idiomaEnCastellano": "Portugués", "idiomaOroginal": "Português"},
            {"indice": 79, "idiomaEnCastellano": "Rumano", "idiomaOroginal": "românesc"},
            {"indice": 80, "idiomaEnCastellano": "Ruso", "idiomaOroginal": "русский"},
            {"indice": 81, "idiomaEnCastellano": "Samoano", "idiomaOroginal": "Samoa"},
            {"indice": 82, "idiomaEnCastellano": "Serbio", "idiomaOroginal": "Српски"},
            {"indice": 83, "idiomaEnCastellano": "Shona", "idiomaOroginal": "Shona"},
            {"indice": 84, "idiomaEnCastellano": "Sindhi", "idiomaOroginal": "سنڌي "},
            {"indice": 85, "idiomaEnCastellano": "Somalí", "idiomaOroginal": "Soomaali"},
            {"indice": 86, "idiomaEnCastellano": "Sotho", "idiomaOroginal": "meridional Sotho ea boroa "},
            {"indice": 87, "idiomaEnCastellano": "Suajili", "idiomaOroginal": "Kiswahili"},
            {"indice": 88, "idiomaEnCastellano": "Sueco", "idiomaOroginal": "Svenska"},
            {"indice": 89, "idiomaEnCastellano": "Sundanés", "idiomaOroginal": "Urang Sunda "},
            {"indice": 90, "idiomaEnCastellano": "Tagalo", "idiomaOroginal": "Tagalog"},
            {"indice": 91, "idiomaEnCastellano": "Tailandés", "idiomaOroginal":  "ไทย"},
            {"indice": 92, "idiomaEnCastellano": "Tamil", "idiomaOroginal": "தமிழ்"},
            {"indice": 93, "idiomaEnCastellano": "Tayiko", "idiomaOroginal": "Точико"},
            {"indice": 94, "idiomaEnCastellano": "Telugu", "idiomaOroginal": "telugu"},
            {"indice": 95, "idiomaEnCastellano": "Turco", "idiomaOroginal": "Türk"},
            {"indice": 96, "idiomaEnCastellano": "Ucraniano", "idiomaOroginal": "Українська "},
            {"indice": 97, "idiomaEnCastellano": "Urdu", "idiomaOroginal": "اردو۔"},
            {"indice": 98, "idiomaEnCastellano": "Uzbeko", "idiomaOroginal": "O'zbek "},
            {"indice": 99, "idiomaEnCastellano": "Vietnamita", "idiomaOroginal": "Tiếng việt nam"},
            {"indice": 100, "idiomaEnCastellano": "Xhosa", "idiomaOroginal": "IsiXhosa "},
            {"indice": 101, "idiomaEnCastellano": "Yidis", "idiomaOroginal": "Yidis"},
            {"indice": 102, "idiomaEnCastellano": "Yoruba", "idiomaOroginal": "Yoruba"},
            {"indice": 103, "idiomaEnCastellano": "Zulú", "idiomaOroginal": "IsiZulu "}
        ]
    } 

    constructor() { }
}
