import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class IdiomaService {

    
    listaDeIdiomas(): any[]{
        return [
            {"indice": 0, "Heteroglotonimo": "Afrikáans*", "Autoglotonimo": "afrikáans "},
            {"indice": 1, "Heteroglotonimo": "Albanés*", "Autoglotonimo": "gjuha shqipë"},
            {"indice": 2, "Heteroglotonimo": "Alemán*", "Autoglotonimo": "deutsch "},
            {"indice": 3, "Heteroglotonimo": "Amárico*", "Autoglotonimo": "አማርኛ "},
            {"indice": 4, "Heteroglotonimo": "Árabe*", "Autoglotonimo": "العربية", "dir":"rtl"},
            {"indice": 5, "Heteroglotonimo": "Armenio*", "Autoglotonimo": "հայերեն լեզու "},
            {"indice": 6, "Heteroglotonimo": "Azerí*", "Autoglotonimo": "Азәрбајҹан дили"},
            {"indice": 7, "Heteroglotonimo": "Bengalí*", "Autoglotonimo": "বাংলা"},
            {"indice": 8, "Heteroglotonimo": "Bielorruso*", "Autoglotonimo": "Беларуская"},
            {"indice": 9, "Heteroglotonimo": "Birmano*", "Autoglotonimo": "မြန်မာ "},
            {"indice": 10, "Heteroglotonimo": "Bosnio*", "Autoglotonimo": "bosanski jezik"},
            {"indice": 11, "Heteroglotonimo": "Búlgaro*", "Autoglotonimo": "български"},
            {"indice": 12, "Heteroglotonimo": "Canarés*", "Autoglotonimo": "ಕನ್ನಡ "},
            {"indice": 13, "Heteroglotonimo": "Catalán*", "Autoglotonimo": "català"},
            {"indice": 14, "Heteroglotonimo": "Cebuano*", "Autoglotonimo": "sugbuanon"},
            {"indice": 15, "Heteroglotonimo": "Checo*", "Autoglotonimo": "Česky"},
            {"indice": 16, "Heteroglotonimo": "Chino (Simplificado)*", "Autoglotonimo":   "汉语"},
            {"indice": 17, "Heteroglotonimo": "Chino (Tradicional)*", "Autoglotonimo":  "漢語"},
            {"indice": 18, "Heteroglotonimo": "Cingalés*", "Autoglotonimo": "සිංහල"},
            {"indice": 19, "Heteroglotonimo": "Coreano*", "Autoglotonimo": "한국어"},
            {"indice": 20, "Heteroglotonimo": "Corso*", "Autoglotonimo": "corsu"},
            {"indice": 21, "Heteroglotonimo": "Criollo*", "Autoglotonimo": "kreyòl ayisyen"},
            {"indice": 22, "Heteroglotonimo": "Croata*", "Autoglotonimo": "hrvatski"},
            {"indice": 23, "Heteroglotonimo": "Danés*", "Autoglotonimo": "dansk"},



            {"indice": 24, "Heteroglotonimo": "Eslovaco*", "Autoglotonimo": "slovenčina, slovenský jazyk"},



            {"indice": 25, "Heteroglotonimo": "Esloveno", "Autoglotonimo": "Slovensko"},
            {"indice": 26, "Heteroglotonimo": "Español", "Autoglotonimo": "Español", "direccion" : "ltr"},
            {"indice": 27, "Heteroglotonimo": "Esperanto", "Autoglotonimo": "Esperanto"},
            {"indice": 28, "Heteroglotonimo": "Estonio", "Autoglotonimo": "Eestlane"},
            {"indice": 29, "Heteroglotonimo": "Euskera", "Autoglotonimo": "Euskera"},
            {"indice": 30, "Heteroglotonimo": "Finés", "Autoglotonimo": "suomalainen"},
            {"indice": 31, "Heteroglotonimo": "Francés", "Autoglotonimo": "Le français"},
            {"indice": 32, "Heteroglotonimo": "Frisón", "Autoglotonimo": "occidental Westerlauwersk"},
            {"indice": 33, "Heteroglotonimo": "Gaélico", "Autoglotonimo": "escocés Gàidhlig na h-Alba"},
            {"indice": 34, "Heteroglotonimo": "Galés", "Autoglotonimo": "Cymraeg"},
            {"indice": 35, "Heteroglotonimo": "Gallego", "Autoglotonimo": "Galego "},
            {"indice": 36, "Heteroglotonimo": "Georgiano", "Autoglotonimo": "ქართული"},
            {"indice": 37, "Heteroglotonimo": "Griego", "Autoglotonimo": "Ελληνικά"},
            {"indice": 38, "Heteroglotonimo": "Guyaratí", "Autoglotonimo": "ગુજરાતí "},
            {"indice": 39, "Heteroglotonimo": "Hausa", "Autoglotonimo": "Hausa "},
            {"indice": 40, "Heteroglotonimo": "Hawaiano", "Autoglotonimo": "ʻ .lelo Hawaiʻi"},
            {"indice": 41, "Heteroglotonimo": "Hebreo", "Autoglotonimo": "עברית ", "dir":"rtl"},
            {"indice": 42, "Heteroglotonimo": "Hindi", "Autoglotonimo": "हिन्दी "},
            {"indice": 43, "Heteroglotonimo": "Hmong", "Autoglotonimo": "Hmong "},
            {"indice": 44, "Heteroglotonimo": "Húngaro", "Autoglotonimo": "magyar "},
            {"indice": 45, "Heteroglotonimo": "Igbo", "Autoglotonimo": "Ndi Igbo"},
            {"indice": 46, "Heteroglotonimo": "Indonesio", "Autoglotonimo": "Orang indonesia"},
            {"indice": 47, "Heteroglotonimo": "Inglés", "Autoglotonimo": "English "},
            {"indice": 48, "Heteroglotonimo": "Irlandés", "Autoglotonimo": "Gaeilge "},
            {"indice": 49, "Heteroglotonimo": "Islandés", "Autoglotonimo": "Íslensku "},
            {"indice": 50, "Heteroglotonimo": "Italiano", "Autoglotonimo": "italiano "},
            {"indice": 51, "Heteroglotonimo": "Japonés", "Autoglotonimo": "日本語 "},
            {"indice": 52, "Heteroglotonimo": "Javanés", "Autoglotonimo": "Basa jawa"},
            {"indice": 53, "Heteroglotonimo": "Jemer", "Autoglotonimo": "ខ្មែរ។ "},
            {"indice": 54, "Heteroglotonimo": "Kazajo", "Autoglotonimo": "Қазақ "},
            {"indice": 55, "Heteroglotonimo": "Kirguís", "Autoglotonimo": "Кыргызстандык "},
            {"indice": 56, "Heteroglotonimo": "Kurdo", "Autoglotonimo": "Kurdî"},
            {"indice": 57, "Heteroglotonimo": "Lao", "Autoglotonimo": "ລາວ "},
            {"indice": 58, "Heteroglotonimo": "Latín", "Autoglotonimo": "Latine"},
            {"indice": 59, "Heteroglotonimo": "Letón", "Autoglotonimo": "Latvietis"},
            {"indice": 60, "Heteroglotonimo": "Lituano", "Autoglotonimo": "Lietuvis"},
            {"indice": 61, "Heteroglotonimo": "Luxemburgués", "Autoglotonimo": "Lëtzebuergesch"},
            {"indice": 62, "Heteroglotonimo": "Macedonio", "Autoglotonimo": "Македонски"},
            {"indice": 63, "Heteroglotonimo": "Malayalam", "Autoglotonimo": "മലയാളം "},
            {"indice": 64, "Heteroglotonimo": "Malayo", "Autoglotonimo": "Melayu"},
            {"indice": 65, "Heteroglotonimo": "Malgache", "Autoglotonimo": "Malgache"},
            {"indice": 66, "Heteroglotonimo": "Maltés", "Autoglotonimo": "Malti"},
            {"indice": 67, "Heteroglotonimo": "Maorí", "Autoglotonimo": "Maori"},
            {"indice": 68, "Heteroglotonimo": "Maratí", "Autoglotonimo":  "मराठी"},
            {"indice": 69, "Heteroglotonimo": "Mongol", "Autoglotonimo": "Монгол"},
            {"indice": 70, "Heteroglotonimo": "Neerlandés", "Autoglotonimo": "Nederlands"},
            {"indice": 71, "Heteroglotonimo": "Nepalí", "Autoglotonimo": "नेपाली"},
            {"indice": 72, "Heteroglotonimo": "Noruego", "Autoglotonimo": "norsk"},
            {"indice": 73, "Heteroglotonimo": "Nyanja", "Autoglotonimo": "Nyanja"},
            {"indice": 74, "Heteroglotonimo": "Panyabí", "Autoglotonimo": "ਪੰਜਾਬੀ"},
            {"indice": 75, "Heteroglotonimo": "Pastún", "Autoglotonimo": "پښتو", "dir":"rtl"},
            {"indice": 76, "Heteroglotonimo": "Persa", "Autoglotonimo": "فارسی", "dir":"rtl"},
            {"indice": 77, "Heteroglotonimo": "Polaco", "Autoglotonimo": "Polski"},
            {"indice": 78, "Heteroglotonimo": "Portugués", "Autoglotonimo": "Português"},
            {"indice": 79, "Heteroglotonimo": "Rumano", "Autoglotonimo": "românesc"},
            {"indice": 80, "Heteroglotonimo": "Ruso", "Autoglotonimo": "русский"},
            {"indice": 81, "Heteroglotonimo": "Samoano", "Autoglotonimo": "Samoa"},
            {"indice": 82, "Heteroglotonimo": "Serbio", "Autoglotonimo": "Српски"},
            {"indice": 83, "Heteroglotonimo": "Shona", "Autoglotonimo": "Shona"},
            {"indice": 84, "Heteroglotonimo": "Sindhi", "Autoglotonimo": "سنڌي ", "dir":"rtl"},
            {"indice": 85, "Heteroglotonimo": "Somalí", "Autoglotonimo": "Soomaali"},
            {"indice": 86, "Heteroglotonimo": "Sotho", "Autoglotonimo": "meridional Sotho ea boroa "},
            {"indice": 87, "Heteroglotonimo": "Suajili", "Autoglotonimo": "Kiswahili"},
            {"indice": 88, "Heteroglotonimo": "Sueco", "Autoglotonimo": "Svenska"},
            {"indice": 89, "Heteroglotonimo": "Sundanés", "Autoglotonimo": "Urang Sunda "},
            {"indice": 90, "Heteroglotonimo": "Tagalo", "Autoglotonimo": "Tagalog"},
            {"indice": 91, "Heteroglotonimo": "Tailandés", "Autoglotonimo":  "ไทย"},
            {"indice": 92, "Heteroglotonimo": "Tamil", "Autoglotonimo": "தமிழ்"},
            {"indice": 93, "Heteroglotonimo": "Tayiko", "Autoglotonimo": "Точико"},
            {"indice": 94, "Heteroglotonimo": "Telugu", "Autoglotonimo": "telugu"},
            {"indice": 95, "Heteroglotonimo": "Turco", "Autoglotonimo": "Türk"},
            {"indice": 96, "Heteroglotonimo": "Ucraniano", "Autoglotonimo": "Українська "},
            {"indice": 97, "Heteroglotonimo": "Urdu", "Autoglotonimo": "اردو۔",  "dir":"rtl"},
            {"indice": 98, "Heteroglotonimo": "Uzbeko", "Autoglotonimo": "O'zbek "},
            {"indice": 99, "Heteroglotonimo": "Vietnamita", "Autoglotonimo": "Tiếng việt nam"},
            {"indice": 100, "Heteroglotonimo": "Xhosa", "Autoglotonimo": "IsiXhosa "},
            {"indice": 101, "Heteroglotonimo": "Yidis", "Autoglotonimo": "ייִדיש",  "dir":"rtl"},
            {"indice": 102, "Heteroglotonimo": "Yoruba", "Autoglotonimo": "Yoruba"},
            {"indice": 103, "Heteroglotonimo": "Zulú", "Autoglotonimo": "IsiZulu "}
        ]
    } 

    constructor() { }
}
