import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class IdiomaService {

    get_idioma_by_indice(indice) {
        return this.listaDeIdiomas().filter(idioma => {
            return idioma.indice === indice;
        })[0]
    }

    idioma_seleccionado = this.get_idioma_by_indice(47)[0]

    seleccionar_idioma(idioma): void
    {
        let vm = this;
        vm.idioma_seleccionado = idioma;
    }
    
    idioma_actual(idioma) : any 
    {
        let vm = this;
        return vm.idioma_seleccionado;
    }

    get_idioma_por_defecto() : any
    {
        let lista_de_idiomas = this.listaDeIdiomas();
        let idiomaPorDefecto = lista_de_idiomas.find(function(element) {
            return element.indice === 47;
        });
        return idiomaPorDefecto;
    }

    listaDeIdiomas(): any[]{
        return [
            {"indice": 0, "Heteroglotonimo": "Afrikáans", "Autoglotonimo": "afrikáans ", "dir":"ltr",
                "Invalid_Title": "Ongeldige titel",
                "Invalid_Year":"Ongeldige jaar",
                "Invalid_Date":"Ongeldige datum",
                "Welcome": "Welkom",
                "Search": "Soek",
                "Order" : "Orde",
                "Ascending order": "Stygende volgorde",
                "Descending order":"Dalende orde",
                "Save": "Save",
                "Cancel": "kanselleer",
                "Success": "sukses",
                "Delete" : "verwyder",
                "Event_saved_successfully": "Gebeurtenis suksesvol gestoor",
                "Warning": "waarskuwing",
                "This action cannot be reversed": "Hierdie aksie kan nie gekeer word nie.",
                "Remove": "verwyder",
                "Title": "Titel",
                "Event": "gebeurtenis",
                "Year": "Jaar",
                "Month": "maand",
                "Day": "dag",
                "Hour": "Uur",
                "Minute": "minuut",
                "Second": "tweede",
                "Add": "Voeg",
                "Select One":"Kies een",
                "Months":[
                    { "value": 0, "name": "Januarie"},
                    { "value": 1, "name": "Februarie"},
                    { "value": 2, "name": "Maart"},
                    { "value": 3, "name": "April"},
                    { "value": 4, "name": "Mei"},
                    { "value": 5, "name": "Junie"},
                    { "value": 6, "name": "Julie"},
                    { "value": 7, "name": "Augustus"},
                    { "value": 8, "name": "September"},
                    { "value": 9, "name": "Oktober"},
                    { "value": 10, "name": "November"},
                    { "value": 11, "name": "Desember"}
                ],
                "Copy": "kopie",
                "Share": "Deel",
                "Accept" : "aanvaar",
                "Edit" : "wysig",
                "event_date": "gebeurtenis datum",
                "Future": "toekoms",
                "Past" : "verlede"
            },
            {"indice": 1, "Heteroglotonimo": "Albanés", "Autoglotonimo": "gjuha shqipë",
                "Invalid_Title": "Titulli i pavlefshëm",
                "Invalid_Year":"Viti i pavlefshëm",
                "Invalid_Date":"Data e pavlefshme",
                "Welcome": "i mirëpritur",
                "Search": "kërkim",
                "Order" : "urdhër",
                "Ascending order": "Rendi i ngritjes",
                "Descending order":"Renditja zbritëse",
                "Save": "Save",
                "Cancel": "anuloj",
                "Success": "Sukses",
                "Delete" : "fshij",
                "Event_saved_successfully": "Ngjarja u ruajt me sukses",
                "Warning": "paralajmërim",
                "This action cannot be reversed": "Ky veprim nuk mund të kthehet",
                "Remove": "heq",
                "Title": "titull",
                "Event": "ngjarje",
                "Year": "vit",
                "Month": "Muaj",
                "Day": "ditë",
                "Hour": "orë",
                "Minute": "minutë",
                "Second": "i dytë",
                "Add": "shtoj",
                "Select One":"Zgjidh nje",
                "Months":[
                    { "value": 0, "name": "janar"},
                    { "value": 1, "name": "shkurt"},
                    { "value": 2, "name": "marsh"},
                    { "value": 3, "name": "prill"},
                    { "value": 4, "name": "Mund"},
                    { "value": 5, "name": "qershor"},
                    { "value": 6, "name": "korrik"},
                    { "value": 7, "name": "gusht"},
                    { "value": 8, "name": "shtator"},
                    { "value": 9, "name": "tetor"},
                    { "value": 10, "name": "nëntor"},
                    { "value": 11, "name": "dhjetor"}
                ],
                "Copy": "kopje",
                "Share": "pjesë",
                "Accept" : "pranoj",
                "Edit" : "redaktoj",
                "event_date": "data e ngjarjes",
                "Future": "i ardhshëm",
                "Past" : "e kaluara"
            },
            {"indice": 2, "Heteroglotonimo": "Alemán", "Autoglotonimo": "deutsch ",
                "Invalid_Title": "Ungültiger Titel",
                "Invalid_Year":"Ungültiges Jahr",
                "Invalid_Date":"Ungültiges Datum",
                "Welcome": "Herzlich willkommen",
                "Search": "Suche",
                "Order" : "Bestellung",
                "Ascending order": "Aufsteigende Reihenfolge",
                "Descending order":"Absteigende Reihenfolge",
                "Save": "sparen",
                "Cancel": "Stornieren",
                "Success": "Erfolg",
                "Delete" : "Löschen",
                "Event_saved_successfully": "Ereignis erfolgreich gespeichert",
                "Warning": "Warnung",
                "This action cannot be reversed": "Diese Aktion kann nicht rückgängig gemacht werden",
                "Remove": "Entfernen",
                "Title": "Titel",
                "Event": "Veranstaltung",
                "Year": "Jahr",
                "Month": "Monat",
                "Day": "Tag",
                "Hour": "Stunde",
                "Minute": "Minute",
                "Second": "Zweite",
                "Add": "Hinzufügen",
                "Select One":"Wähle eins",
                "Months":[
                    { "value": 0, "name": "Januar"},
                    { "value": 1, "name": "Februar"},
                    { "value": 2, "name": "März"},
                    { "value": 3, "name": "April"},
                    { "value": 4, "name": "Kann"},
                    { "value": 5, "name": "Juni"},
                    { "value": 6, "name": "Juli"},
                    { "value": 7, "name": "August"},
                    { "value": 8, "name": "September"},
                    { "value": 9, "name": "Oktober"},
                    { "value": 10, "name": "November"},
                    { "value": 11, "name": "Dezember"}
                ],
                "Copy": "Kopieren",
                "Share": "Aktie",
                "Accept" : "Akzeptieren",
                "Edit" : "Bearbeiten",
                "event_date": "Veranstaltungsdatum",
                "Future": "Zukunft",
                "Past" : "Vergangenheit"
            },
            {"indice": 3, "Heteroglotonimo": "Amárico", "Autoglotonimo": "አማርኛ ",
                "Invalid_Title": "ልክ ያልሆነ ርዕስ",
                "Invalid_Year":"ልክ ያልሆነ ዓመት",
                "Invalid_Date":"ልክ ያልሆነ ቀን",
                "Welcome": "እንኳን ደህና መጣህ",
                "Search": "ይፈልጉ",
                "Order" : "ትእዛዝ",
                "Ascending order": "ቅደም ተከተል መምጣት",
                "Descending order":"ትዕዛዛት ቅደም ተከተል",
                "Save": "አስቀምጥ",
                "Cancel": "ይቅር",
                "Success": "ስኬት",
                "Delete" : "ሰርዝ",
                "Event_saved_successfully": "ዝግጅት በተሳካ ሁኔታ ተቀም savedል",
                "Warning": "ማስጠንቀቂያ",
                "This action cannot be reversed": "ይህ እርምጃ ሊቀለበስ አይችልም",
                "Remove": "ያስወግዱ",
                "Title": "ርዕስ",
                "Event": "ክስተት",
                "Year": "አመት",
                "Month": "ወር",
                "Day": "ቀን",
                "Hour": "ሰአት",
                "Minute": "ደቂቃ",
                "Second": "ሁለተኛ",
                "Add": "ያክሉ",
                "Select One":"አ ን ድ ም ረ ጥ",
                "Months":[
                    { "value": 0, "name": "ጥር"},
                    { "value": 1, "name": "የካቲት"},
                    { "value": 2, "name": "መጋቢት"},
                    { "value": 3, "name": "ሚያዚያ"},
                    { "value": 4, "name": "ግንቦት"},
                    { "value": 5, "name": "ሰኔ"},
                    { "value": 6, "name": "ሀምሌ"},
                    { "value": 7, "name": "ነሐሴ"},
                    { "value": 8, "name": "መስከረም"},
                    { "value": 9, "name": "ጥቅምት"},
                    { "value": 10, "name": "ህዳር"},
                    { "value": 11, "name": "ታህሳስ"}
                ],
                "Copy": "ቅዳ",
                "Share": "ያጋሩ",
                "Accept" : "ተቀበል",
                "Edit" : "ያርትዑ",
                "event_date": "የዝግጅት ቀን",
                "Future": "ወደፊት",
                "Past" : "ያለፈው"
            },
            {"indice": 4, "Heteroglotonimo": "Árabe", "Autoglotonimo": "العربية", "dir":"rtl",
                "Invalid_Title": "عنوان غير صالح",
                "Invalid_Year":"سنة غير صالحة",
                "Invalid_Date":"تاريخ غير صالح",
                "Welcome": "أهلا بك",
                "Search": "بحث",
                "Order" : "طلب",
                "Ascending order": "ترتيب تصاعدي",
                "Descending order":"تنازليا",
                "Save": "حفظ",
                "Cancel": "إلغاء",
                "Success": "نجاح",
                "Delete" : "حذف",
                "Event_saved_successfully": "تم حفظ الحدث بنجاح",
                "Warning": "تحذير",
                "This action cannot be reversed": "لا يمكن عكس هذا الإجراء",
                "Remove": "إزالة",
                "Title": "عنوان",
                "Event": "حدث",
                "Year": "عام",
                "Month": "شهر",
                "Day": "يوم",
                "Hour": "ساعة",
                "Minute": "دقيقة",
                "Second": "ثانيا",
                "Add": "إضافة",
                "Select One":"اختيار واحد",
                "Months":[
                    { "value": 0, "name": "كانون الثاني"},
                    { "value": 1, "name": "شهر فبراير"},
                    { "value": 2, "name": "مارس"},
                    { "value": 3, "name": "أبريل"},
                    { "value": 4, "name": "مايو"},
                    { "value": 5, "name": "يونيو"},
                    { "value": 6, "name": "يوليو"},
                    { "value": 7, "name": "أغسطس"},
                    { "value": 8, "name": "سبتمبر"},
                    { "value": 9, "name": "شهر اكتوبر"},
                    { "value": 10, "name": "شهر نوفمبر"},
                    { "value": 11, "name": "ديسمبر"}
                ],
                "Copy": "نسخ",
                "Share": "شارك",
                "Accept" : "قبول",
                "Edit" : "تعديل",
                "event_date": "تاريخ الحدث",
                "Future": "مستقبل",
                "Past" : "الماضي"
            },
            {"indice": 5, "Heteroglotonimo": "Armenio", "Autoglotonimo": "հայերեն լեզու ",
                "Invalid_Title": "Անվավեր վերնագիր",
                "Invalid_Year":"Անվավեր տարի",
                "Invalid_Date":"Անվավեր ամսաթիվ",
                "Welcome": "Բարի գալուստ",
                "Search": "Որոնել",
                "Order" : "Պատվեր",
                "Ascending order": "Աճման կարգով",
                "Descending order":"Նվազող կարգ",
                "Save": "Խնայել",
                "Cancel": "Չեղարկել",
                "Success": "Հաջողություն",
                "Delete" : "Նջել",
                "Event_saved_successfully": "Իրադարձությունը հաջողությամբ պահպանվեց",
                "Warning": "Զգուշացում",
                "This action cannot be reversed": "Այս գործողությունը չի կարող հետ բերվել",
                "Remove": "Հեռացրեք",
                "Title": "Կոչում",
                "Event": "Իրադարձություն",
                "Year": "Տարի",
                "Month": "Ամիս",
                "Day": "Օր",
                "Hour": "Ժամ",
                "Minute": "Րոպե",
                "Second": "Երկրորդ",
                "Add": "Ավելացնել",
                "Select One":"Ընտրիր մեկը",

                "Months":[
                    { "value": 0, "name": "Հունվար"},
                    { "value": 1, "name": "Փետրվար"},
                    { "value": 2, "name": "Մարտ"},
                    { "value": 3, "name": "Ապրիլ"},
                    { "value": 4, "name": "Մայիս"},
                    { "value": 5, "name": "Հունիս"},
                    { "value": 6, "name": "Հուլիս"},
                    { "value": 7, "name": "Օգոստոս"},
                    { "value": 8, "name": "Սեպտեմբեր"},
                    { "value": 9, "name": "Հոկտեմբեր"},
                    { "value": 10, "name": "Նոյեմբեր"},
                    { "value": 11, "name": "Դեկտեմբեր"}
                ],
                "Copy": "Պատճենել",
                "Share": "Կիսվիր",
                "Accept" : "Ընդունել",
                "Edit" : "Խմբագրել",
                "event_date": "իրադարձության ամսաթիվը",
                "Future": "Ապագա",
                "Past" : "Անցյալ",
            },
            {"indice": 6, "Heteroglotonimo": "Azerí", "Autoglotonimo": "Азәрбајҹан дили",
                "Invalid_Title": "Yanlış Başlıq",
                "Invalid_Year":"Yanlış İl",
                "Invalid_Date":"Yanlış tarix",
                "Welcome": "Xoş gəldiniz",
                "Search": "Axtarış",
                "Order" : "Sifariş verin",
                "Ascending order": "Artan sifariş",
                "Descending order":"Azalan sifariş",
                "Save": "Yadda saxla",
                "Cancel": "Ləğv et",
                "Success": "Uğur",
                "Delete" : "Silin",
                "Event_saved_successfully": "Tədbir uğurla qeyd olundu",
                "Warning": "Xəbərdarlıq",
                "This action cannot be reversed": "Bu hərəkəti geri qaytarmaq olmur",
                "Remove": "Sil",
                "Title": "Başlıq",
                "Event": "Hadisə",
                "Year": "İl",
                "Month": "Ay",
                "Day": "Gün",
                "Hour": "Saat",
                "Minute": "Dəqiqə",
                "Second": "İkinci",
                "Add": "Əlavə edin",
                "Select One": "Birini seçin",
                "Months":[
                    { "value": 0, "name": "yanvar"},
                    { "value": 1, "name": "Fevral"},
                    { "value": 2, "name": "mart"},
                    { "value": 3, "name": "Aprel"},
                    { "value": 4, "name": "Bilər"},
                    { "value": 5, "name": "İyun"},
                    { "value": 6, "name": "İyul"},
                    { "value": 7, "name": "Avqust"},
                    { "value": 8, "name": "Sentyabr"},
                    { "value": 9, "name": "oktyabr"},
                    { "value": 10, "name": "Noyabr"},
                    { "value": 11, "name": "Dekabr"}
                ],
                "Copy": "Surəti",
                "Share": "Paylaşın",
                "Accept" : "Qəbul edin",
                "Edit" : "Redaktə edin",
                "event_date": "hadisə tarixi",
                "Future": "Gələcək",
                "Past" : "Keçmiş"
            },
            {"indice": 7, "Heteroglotonimo": "Bengalí", "Autoglotonimo": "বাংলা",
                "Invalid_Title": "অবৈধ শিরোনাম",
                "Invalid_Year":"অবৈধ বছর",
                "Invalid_Date":"অবৈধ তারিখ",
                "Welcome": "স্বাগত",
                "Search": "অনুসন্ধান",
                "Order" : "ক্রম",
                "Ascending order": "উর্দ্ধক্রমানুসারে",
                "Descending order":"অবতরণ ক্রম",
                "Save": "সংরক্ষণ",
                "Cancel": "বাতিল",
                "Success": "সাফল্য",
                "Delete" : "মুছে ফেলা",
                "Event_saved_successfully": "ইভেন্ট সফলভাবে সংরক্ষণ করা হয়েছে",
                "Warning": "সতর্কতা",
                "This action cannot be reversed": "এই ক্রিয়াটি বিপরীত করা যাবে না",
                "Remove": "অপসারণ",
                "Title": "শিরোনাম",
                "Event": "ঘটনা",
                "Year": "বছর",
                "Month": "মাস",
                "Day": "দিন",
                "Hour": "ঘন্টা",
                "Minute": "মিনিট",
                "Second": "দ্বিতীয়",
                "Add": "যোগ",
                "Select One": "একটা নির্বাচন করুন",
                "Months":[
                    { "value": 0, "name": "জানুয়ারী"},
                    { "value": 1, "name": "ফেব্রুয়ারি"},
                    { "value": 2, "name": "মার্চ"},
                    { "value": 3, "name": "এপ্রিল"},
                    { "value": 4, "name": "মে"},
                    { "value": 5, "name": "জুন"},
                    { "value": 6, "name": "জুলাই"},
                    { "value": 7, "name": "অগাস্ট"},
                    { "value": 8, "name": "সেপ্টেম্বর"},
                    { "value": 9, "name": "অক্টোবর"},
                    { "value": 10, "name": "নভেম্বর"},
                    { "value": 11, "name": "ডিসেম্বর"}
                ],
                "Copy": "কপি",
                "Share": "ভাগ",
                "Accept" : "গ্রহণ করা",
                "Edit" : "সম্পাদন করা",
                "event_date": "গফভ",
                "Future": "ভবিষ্যৎ",
                "Past" : "গত"
            },
            {"indice": 8, "Heteroglotonimo": "Bielorruso", "Autoglotonimo": "Беларуская",
                "Invalid_Title": "Несапраўдны загаловак",
                "Invalid_Year":"Несапраўдны год",
                "Invalid_Date":"Няправільная дата",
                "Welcome": "Сардэчна запрашаем",
                "Search": "Пошук",
                "Order" : "Ордэн",
                "Ascending order": "Парадак урастання",
                "Descending order":"Парадак памяншэння",
                "Save": "Захаваць",
                "Cancel": "Адмяніць",
                "Success": "Поспех",
                "Delete" : "Выдаліць",
                "Event_saved_successfully": "Падзея паспяхова захавана",
                "Warning": "Папярэджанне",
                "This action cannot be reversed": "Гэтае дзеянне нельга адмяніць",
                "Remove": "Выдаліць",
                "Title": "Назва",
                "Event": "Падзея",
                "Year": "Год",
                "Month": "Месяц",
                "Day": "Дзень",
                "Hour": "Гадзіна",
                "Minute": "Хвілінка",
                "Second": "Другі",
                "Add": "Дадаць",
                "Select One": "Абярыце Адзін",
                "Months":[
                    { "value": 0, "name": "Студзень"},
                    { "value": 1, "name": "Люты"},
                    { "value": 2, "name": "Сакавік"},
                    { "value": 3, "name": "Красавік"},
                    { "value": 4, "name": "Мая"},
                    { "value": 5, "name": "Чэрвень"},
                    { "value": 6, "name": "Ліпень"},
                    { "value": 7, "name": "Жнівень"},
                    { "value": 8, "name": "Верасень"},
                    { "value": 9, "name": "Кастрычніцкая"},
                    { "value": 10, "name": "Лістапада"},
                    { "value": 11, "name": "Снежань"}
                ],
                "Copy": "Копія",
                "Share": "Падзяліцца",
                "Accept" : "Прымі",
                "Edit" : "Рэдагаваць",
                "event_date": "дата падзей",
                "Future": "Будучыня",
                "Past" : "Мінулае"
            },
            {"indice": 9, "Heteroglotonimo": "Birmano", "Autoglotonimo": "မြန်မာ ",
                "valid_Title": "မမှန်ကန်သောခေါင်းစဉ်",
                "Invalid_Year":"မမှန်ကန်သောနှစ်",
                "Invalid_Date":"မမှန်ကန်သောနေ့စွဲ",
                "Welcome": "ကြိုဆိုပါတယ်",
                "Search": "ရှာပါ",
                "Order" : "အမှာစာ",
                "Ascending order": "အမှာတက်သည်",
                "Descending order": "အမိန့်ဆင်းခြင်း",
                "Save": "သိမ်းဆည်းပါ",
                "Cancel": "ပယ်ဖျက်ပါ",
                "Success": "အောင်မြင်သည်",
                "Delete" : "ဖျက်ပါ",
                "Event_saved_successfully": "ဖြစ်ရပ်ကိုအောင်မြင်စွာသိမ်းဆည်းပြီး",
                "Warning": "သတိပေးချက်",
                "This action cannot be reversed": "ဒီလုပ်ဆောင်ချက်ကိုပြောင်းပြန်မရပါ",
                "Remove": "ဖယ်ရှားပါ",
                "Title": "ခေါင်းစဥ်",
                "Event": "အဖြစ်အပျက်",
                "Year": "နှစ်",
                "Month": "လ",
                "Day": "နေ့",
                "Hour": "နာရီ",
                "Minute": "မိနစ်",
                "Second": "ဒုတိယ",
                "Add": "ထည့်ပါ",
                "Select One": "တစ်ခုရွေးပါ",
                "Months":[
                    { "value": 0, "name": "ဇန်နဝါရီလ"},
                    { "value": 1, "name": "ဖေဖော်ဝါရီလ"},
                    { "value": 2, "name": "မတ်လ"},
                    { "value": 3, "name": "ပြီလ"},
                    { "value": 4, "name": "မေလ"},
                    { "value": 5, "name": "ဇွန်"},
                    { "value": 6, "name": "ဇူလိုင်လ"},
                    { "value": 7, "name": "သြဂုတ်လ"},
                    { "value": 8, "name": "စက်တင်ဘာ"},
                    { "value": 9, "name": "အောက်တိုဘာ"},
                    { "value": 10, "name": "နိုဝင်ဘာ"},
                    { "value": 11, "name": "ဒီဇင်ဘာ"}
                ],
                "Copy": "ကူးပါ",
                "Share": "မျှဝေပါ",
                "Accept" : "လက်ခံသည်",
                "Edit" : "တည်းဖြတ်ပါ",
                "event_date": "အဖြစ်အပျက်ရက်စွဲ",
                "Future": "အနာဂတ်",
                "Past" : "အတိတ်"
            },
            {"indice": 10, "Heteroglotonimo": "Bosnio", "Autoglotonimo": "bosanski jezik",
                "Invalid_Title": "Nevažeći naslov",
                "Invalid_Year":"Nevažeća godina",
                "Invalid_Date":"Nevažeći datum",
                "Welcome": "Dobrodošli",
                "Search": "Traži",
                "Order" : "Naredba",
                "Ascending order": "Rastući poredak",
                "Descending order": "Nadajući poredak",
                "Save": "Spremi",
                "Cancel": "Otkaži",
                "Success": "Uspeh",
                "Delete" : "Izbriši",
                "Event_saved_successfully": "Događaj je uspješno spremljen",
                "Warning": "Upozorenje",
                "This action cannot be reversed": "Ova akcija se ne može preokrenuti",
                "Remove": "Uklonite",
                "Title": "Naslov",
                "Event": "Događaj",
                "Year": "Godina",
                "Month": "Mesec",
                "Day": "Dan",
                "Hour": "Sat",
                "Minute": "Minut",
                "Second": "Sekunda",
                "Add": "Dodati",
                "Select One": "Izaberi jedno",
                "Months":[
                    { "value": 0, "name": "Januar"},
                    { "value": 1, "name": "februar"},
                    { "value": 2, "name": "Marta"},
                    { "value": 3, "name": "Aprila"},
                    { "value": 4, "name": "Maja"},
                    { "value": 5, "name": "Juna"},
                    { "value": 6, "name": "Jula"},
                    { "value": 7, "name": "Avgusta"},
                    { "value": 8, "name": "Septembra"},
                    { "value": 9, "name": "Oktobar"},
                    { "value": 10, "name": "Novembra"},
                    { "value": 11, "name": "Prosinca"}
                ],
                "Copy": "Kopiraj",
                "Share": "Podijeli",
                "Accept" : "Prihvati",
                "Edit" : "Uredi",
                "event_date": "datum događaja",
                "Future": "Budućnost",
                "Past" : "Prošlost"
            },
            {"indice": 11, "Heteroglotonimo": "Búlgaro", "Autoglotonimo": "български",
                "Invalid_Title": "Невалидно заглавие",
                "Invalid_Year":"Невалидна година",
                "Invalid_Date":"Невалидна дата",
                "Welcome": "Добре дошли",
                "Search": "Търсене",
                "Order" : "Поръчка",
                "Ascending order": "Възходящ ред",
                "Descending order": "Низходящ ред",
                "Save": "Запази",
                "Cancel": "Отказ",
                "Success": "успех",
                "Delete" : "Изтрий",
                "Event_saved_successfully": "Събитието бе запазено успешно",
                "Warning": "Внимание",
                "This action cannot be reversed": "Това действие не може да бъде обърнато",
                "Remove": "Премахване",
                "Title": "Заглавие",
                "Event": "събитие",
                "Year": "година",
                "Month": "месец",
                "Day": "ден",
                "Hour": "час",
                "Minute": "минута",
                "Second": "втори",
                "Add": "Добави",
                "Select One": "Избери един",
                "Months":[
                    { "value": 0, "name": "януари"},
                    { "value": 1, "name": "февруари"},
                    { "value": 2, "name": "Март"},
                    { "value": 3, "name": "април"},
                    { "value": 4, "name": "Може"},
                    { "value": 5, "name": "юни"},
                    { "value": 6, "name": "Юли"},
                    { "value": 7, "name": "Август"},
                    { "value": 8, "name": "Септември"},
                    { "value": 9, "name": "октомври"},
                    { "value": 10, "name": "ноември"},
                    { "value": 11, "name": "декември"}
                ],
                "Copy": "копие",
                "Share": "Дял",
                "Accept" : "приемам",
                "Edit" : "редактиране",
                "event_date": "дата на събитие",
                "Future": "бъдеще",
                "Past" : "минало"
            },
            /*{"indice": 12, "Heteroglotonimo": "Canarés", "Autoglotonimo": "ಕನ್ನಡ "},
            {"indice": 13, "Heteroglotonimo": "Catalán", "Autoglotonimo": "català"},
            {"indice": 14, "Heteroglotonimo": "Cebuano", "Autoglotonimo": "sugbuanon"},
            {"indice": 15, "Heteroglotonimo": "Checo", "Autoglotonimo": "Česky"},
            {"indice": 16, "Heteroglotonimo": "Chino (Simplificado)", "Autoglotonimo":   "汉语"},
            {"indice": 17, "Heteroglotonimo": "Chino (Tradicional)", "Autoglotonimo":  "漢語"},
            {"indice": 18, "Heteroglotonimo": "Cingalés", "Autoglotonimo": "සිංහල"},
            {"indice": 19, "Heteroglotonimo": "Coreano", "Autoglotonimo": "한국어"},
            {"indice": 20, "Heteroglotonimo": "Corso", "Autoglotonimo": "corsu"},
            {"indice": 21, "Heteroglotonimo": "Criollo", "Autoglotonimo": "kreyòl ayisyen"},
            {"indice": 22, "Heteroglotonimo": "Croata", "Autoglotonimo": "hrvatski"},
            {"indice": 23, "Heteroglotonimo": "Danés", "Autoglotonimo": "dansk"},
            {"indice": 24, "Heteroglotonimo": "Eslovaco", "Autoglotonimo": "slovenčina, slovenský jazyk"},
            {"indice": 25, "Heteroglotonimo": "Esloveno", "Autoglotonimo": "slovenščina"},*/
            {
                "indice": 26, "Heteroglotonimo": "Español", "Autoglotonimo": "Español", "dir":"ltr",
                "Invalid_Title": "Título inválido",
                "Invalid_Year": "Año inválido",
                "Invalid_Date": "Fecha Inválida",
                "Welcome": "Bienvenido",
                "Search": "Buscar",
                "Order" : "Orden",
                "Ascending order": "Order ascendente",
                "Descending order": "Order descendente",
                "Save": "Guardar",
                "Cancel": "Cancelar",
                "Success": "Éxito",
                "Delete" : "Eliminar",
                "Event_saved_successfully": "Evento guardado con éxito",
                "Warning": "Advertencia",
                "This action cannot be reversed": "Esta acción no puede ser revertida.",
                "Remove": "Retirar",
                "Title": "Título",
                "Event": "Evento",
                "Year": "Año",
                "Month": "Mes",
                "Day": "Día",
                "Hour": "Hora",
                "Minute": "Minuto",
                "Second": "Segundo",
                "Add": "Agregar",
                "Select One": "Seleccione uno",
                "Months":[
                    { "value": 0, "name": "Enero" },
                    { "value": 1, "name": "Febrero" },
                    { "value": 2, "name": "Marzo" },
                    { "value": 3, "name": "Abril" },
                    { "value": 4, "name": "Mayo"  },
                    { "value": 5, "name": "Junio" },
                    { "value": 6, "name": "Julio" },
                    { "value": 7, "name": "Agosto" },
                    { "value": 8, "name": "Septiembre" },
                    { "value": 9, "name": "Octubre" },
                    { "value": 10, "name": "Noviembre" },
                    { "value": 11, "name": "Diciembre" }
                ],
                "Copy": "Copiar",
                "Share": "Compartir",
                "Accept" : "Aceptar",
                "Edit" : "Editar",
                "event_date" : "Fecha del evento",
                "Future": "Futuro",
                "Past" : "Pasado"
            },
            /*{"indice": 27, "Heteroglotonimo": "Esperanto", "Autoglotonimo": "Lingvo Internacia"},
            {"indice": 28, "Heteroglotonimo": "Estonio", "Autoglotonimo": "eesti keel"},
            {"indice": 29, "Heteroglotonimo": "Euskera", "Autoglotonimo": "Euskara"},
            {"indice": 30, "Heteroglotonimo": "Finés", "Autoglotonimo": "suomen kieli"},
            {"indice": 31, "Heteroglotonimo": "Francés", "Autoglotonimo": "Français"},
            {"indice": 32, "Heteroglotonimo": "Frisón", "Autoglotonimo": "Frysk, Friisk, Fräisk"},
            {"indice": 33, "Heteroglotonimo": "Gaélico", "Autoglotonimo": "Gàidhlig"},
            {"indice": 34, "Heteroglotonimo": "Galés", "Autoglotonimo": "Cymraeg"},
            {"indice": 35, "Heteroglotonimo": "Gallego", "Autoglotonimo": "Galego"},
            {"indice": 36, "Heteroglotonimo": "Georgiano", "Autoglotonimo": "ქართული"},
            {"indice": 37, "Heteroglotonimo": "Griego", "Autoglotonimo": "Ελληνικά"},
            {"indice": 38, "Heteroglotonimo": "Guyaratí", "Autoglotonimo": "ગુજરાતી"},
            {"indice": 39, "Heteroglotonimo": "Hausa", "Autoglotonimo": "Hausa "},
            {"indice": 40, "Heteroglotonimo": "Hawaiano", "Autoglotonimo": "‘Ōlelo Hawai‘i"},
            */
            {"indice": 41, "Heteroglotonimo": "Hebreo", "Autoglotonimo": "עִבְרִית ", "dir":"rtl",
                "Invalid_Title":"כותרת לא חוקית",
                "Invalid_Year":"שנה לא חוקית",
                "Invalid_Date":"תאריך לא חוקי",
                "Welcome":"ברוך הבא",
                "Search":"לחפש",
                "Order":"להזמין",
                "Ascending order":"בסדר עולה",
                "Descending order":"סדר יורד",
                "Save":"לשמור",
                "Cancel":"בטל",
                "Success":"הצלחה",
                "Delete":"מחק",
                "Event_saved_successfully":"האירוע נשמר בהצלחה",
                "Warning":"אזהרה",
                "This action cannot be reversed":"לא ניתן לבטל פעולה זו",
                "Remove":"הסר",
                "Title":"כותרת",
                "Event":"אירוע",
                "Year":"שנה",
                "Month":"חודש",
                "Day":"יום",
                "Hour":"שעה",
                "Minute":"דקה",
                "Second":"שני",
                "Add":"הוסף",
                "Select One":"תבחר אחד",
                "Months":[
                    { "value": 0, "name": "ינואר" },
                    { "value": 1, "name": "פברואר" },
                    { "value": 2, "name": "מרץ" },
                    { "value": 3, "name": "אפריל" },
                    { "value": 4, "name": "מאי" },
                    { "value": 5, "name": "יוני" },
                    { "value": 6, "name": "יולי" },
                    { "value": 7, "name": "אוגוסט" },
                    { "value": 8, "name": "ספטמבר" },
                    { "value": 9, "name": "אוקטובר" },
                    { "value": 10, "name": "נובמבר" },
                    { "value": 11, "name": "דצמבר"  }
                ],
                "Copy": "עותק",
                "Share": "שתף",
                "Accept": "קבל",
                "Edit": "ערוך",
                "event_date": "תאריך אירוע",
                "Future": "עתיד",
                "Past": "עבר"
            },
            /*
            {"indice": 42, "Heteroglotonimo": "Hindi", "Autoglotonimo": "हिन्दी"},
            {"indice": 43, "Heteroglotonimo": "Hmong", "Autoglotonimo": "Hmong "},
            {"indice": 44, "Heteroglotonimo": "Húngaro", "Autoglotonimo": "magyar "},
            {"indice": 45, "Heteroglotonimo": "Igbo", "Autoglotonimo": "asụsụ Ndi Igbo"},
            {"indice": 46, "Heteroglotonimo": "Indonesio", "Autoglotonimo": "bahasa Indonesia"},*/
            {
                "indice": 47, "Heteroglotonimo": "Inglés", "Autoglotonimo": "English", "dir":"ltr",
                "Invalid_Title": "Invalid Title",
                "Invalid_Year": "Invalid Year",
                "Invalid_Date": "Invalid Date",
                "Welcome": "Welcome",
                "Search": "Search",
                "Order" : "Order",
                "Ascending order": "Ascending order",
                "Descending order": "Descending order",
                "Save": "Save",
                "Cancel": "Cancel",
                "Success": "Success",
                "Delete" : "Delete",
                "Event_saved_successfully": "Event saved successfully",
                "Warning": "Warning",
                "This action cannot be reversed": "This action cannot be reversed",
                "Remove": "Remove",
                "Title": "Title",
                "Event": "Event",
                "Year": "Year",
                "Month": "Month",
                "Day": "Day",
                "Hour": "Hour",
                "Minute": "Minute",
                "Second": "Second",
                "Add": "Add",
                "Select One": "Select One",
                "Months":[
                    { "value": 0, "name": "January" },
                    { "value": 1, "name": "February"},
                    { "value": 2, "name": "March" },
                    { "value": 3, "name": "April" },
                    { "value": 4, "name": "May"  },
                    { "value": 5, "name": "June" },
                    { "value": 6, "name": "July" },
                    { "value": 7, "name": "August" },
                    { "value": 8, "name": "September" },
                    { "value": 9, "name": "October" },
                    { "value": 10, "name": "November" },
                    { "value": 11, "name": "December" }
                ],
                "Copy": "Copy",
                "Share": "Share",
                "Accept" : "Accept",
                "Edit" : "Edit",
                "event_date" : "Event date",
                "Future": "Future",
                "Past" : "Past"
            },
            /*{"indice": 48, "Heteroglotonimo": "Irlandés", "Autoglotonimo": "Gaeilge"},
            {"indice": 49, "Heteroglotonimo": "Islandés", "Autoglotonimo": "íslenska"},
            {"indice": 50, "Heteroglotonimo": "Italiano", "Autoglotonimo": "italiano "},
            {"indice": 51, "Heteroglotonimo": "Japonés", "Autoglotonimo": "日本語"},
            {"indice": 52, "Heteroglotonimo": "Javanés", "Autoglotonimo": "Basa Jawa, Basa Jawi"},
            {"indice": 53, "Heteroglotonimo": "Jemer", "Autoglotonimo": "ខ្មែរ។ "},
            {"indice": 54, "Heteroglotonimo": "Kazajo", "Autoglotonimo": "Қазақ тілі"},
            {"indice": 55, "Heteroglotonimo": "Kirguís", "Autoglotonimo": "кыргыз тили"},
            {"indice": 56, "Heteroglotonimo": "Kurdo", "Autoglotonimo": "Kurdî"},
            {"indice": 57, "Heteroglotonimo": "Lao", "Autoglotonimo": "ພາສາລາວ"},
            {"indice": 58, "Heteroglotonimo": "Latín", "Autoglotonimo": "latinō"},
            {"indice": 59, "Heteroglotonimo": "Letón", "Autoglotonimo": "Latviešu valoda"},
            {"indice": 60, "Heteroglotonimo": "Lituano", "Autoglotonimo": "Lietuvių kalba"},
            {"indice": 61, "Heteroglotonimo": "Luxemburgués", "Autoglotonimo": "Lëtzebuergesch"},
            {"indice": 62, "Heteroglotonimo": "Macedonio", "Autoglotonimo": "Македонски"},
            {"indice": 63, "Heteroglotonimo": "Malayalam", "Autoglotonimo": "മലയാളം"},
            {"indice": 64, "Heteroglotonimo": "Malayo", "Autoglotonimo": "Bahasa Melayu"},
            {"indice": 65, "Heteroglotonimo": "Malgache", "Autoglotonimo": "Malagasy"},
            {"indice": 66, "Heteroglotonimo": "Maltés", "Autoglotonimo": "l-ilsien Malti"},
            {"indice": 67, "Heteroglotonimo": "Maorí", "Autoglotonimo": "reo māori"},
            {"indice": 68, "Heteroglotonimo": "Maratí", "Autoglotonimo":  "मराठी"},
            {"indice": 69, "Heteroglotonimo": "Mongol", "Autoglotonimo": "Монгол"},
            {"indice": 70, "Heteroglotonimo": "Neerlandés", "Autoglotonimo": "Nederlands"},
            {"indice": 71, "Heteroglotonimo": "Nepalí", "Autoglotonimo": "नेपाली"},
            {"indice": 72, "Heteroglotonimo": "Noruego", "Autoglotonimo": "Norsk"},
            {"indice": 73, "Heteroglotonimo": "Nyanja", "Autoglotonimo": "chinyanja / chicheŵa"},
            {"indice": 74, "Heteroglotonimo": "Panyabí", "Autoglotonimo": "ਪੰਜਾਬੀ"},
            {"indice": 75, "Heteroglotonimo": "Pastún", "Autoglotonimo": "پښتو", "dir":"rtl"},
            {"indice": 76, "Heteroglotonimo": "Persa", "Autoglotonimo": "فارسی", "dir":"rtl"},
            {"indice": 77, "Heteroglotonimo": "Polaco", "Autoglotonimo": "Polski"},
            {"indice": 78, "Heteroglotonimo": "Portugués", "Autoglotonimo": "Português"},
            {"indice": 79, "Heteroglotonimo": "Rumano", "Autoglotonimo": "românesc"},
            {"indice": 80, "Heteroglotonimo": "Ruso", "Autoglotonimo": "Русский язык"},
            {"indice": 81, "Heteroglotonimo": "Samoano", "Autoglotonimo": "gagana Samoa"},
            {"indice": 82, "Heteroglotonimo": "Serbio", "Autoglotonimo": "Cрпски / Srpski"},
            {"indice": 83, "Heteroglotonimo": "Shona", "Autoglotonimo": "Shona"},
            {"indice": 84, "Heteroglotonimo": "Sindhi", "Autoglotonimo": "سنڌي ", "dir":"rtl"},
            {"indice": 85, "Heteroglotonimo": "Somalí", "Autoglotonimo": "Af-Soomaali"},
            {"indice": 86, "Heteroglotonimo": "Sotho", "Autoglotonimo": "seSotho"},
            {"indice": 87, "Heteroglotonimo": "Suajili", "Autoglotonimo": "Kiswahili"},
            {"indice": 88, "Heteroglotonimo": "Sueco", "Autoglotonimo": "Svenska"},
            {"indice": 89, "Heteroglotonimo": "Sundanés", "Autoglotonimo": "basa Sunda"},
            {"indice": 90, "Heteroglotonimo": "Tagalo", "Autoglotonimo": "Wikang tagalog"},
            {"indice": 91, "Heteroglotonimo": "Tailandé*s", "Autoglotonimo":  "ภาษาไทย"},
            {"indice": 92, "Heteroglotonimo": "Tamil", "Autoglotonimo": "தமிழ்"},
            {"indice": 93, "Heteroglotonimo": "Tayiko", "Autoglotonimo": "Тоҷикӣ / Todžikī"},
            {"indice": 94, "Heteroglotonimo": "Telugu", "Autoglotonimo": "తెలుగు"},
            {"indice": 95, "Heteroglotonimo": "Turco", "Autoglotonimo": "Türkçe, türk dili"},
            {"indice": 96, "Heteroglotonimo": "Ucraniano", "Autoglotonimo": "Українська мова / Ukraïns'ka mova"},
            {"indice": 97, "Heteroglotonimo": "Urdu", "Autoglotonimo": "اردو۔",  "dir":"rtl"},
            {"indice": 98, "Heteroglotonimo": "Uzbeko", "Autoglotonimo": "O'zbek"},
            {"indice": 99, "Heteroglotonimo": "Vietnamita", "Autoglotonimo": "Tiếng việt nam"},
            {"indice": 100, "Heteroglotonimo": "Xhosa", "Autoglotonimo": "IsiXhosa"},
            {"indice": 101, "Heteroglotonimo": "Yidis", "Autoglotonimo": 'ייִדיש  ', 'dir':"rtl"},
            {"indice": 102, "Heteroglotonimo": "Yoruba", "Autoglotonimo": "Èdèe yorùbá"},
            {"indice": 103, "Heteroglotonimo": "Zulú", "Autoglotonimo": "IsiZulu "}*/
        ]
    } 

    constructor() { }
}
